spring:
  application:
    name: eureka-cluster
    
---
spring:
  profiles: eureka1
server:
  port: 8761
eureka:
  instance:
    hostname: eureka1
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka2:8762/eureka,http://eureka3:8763/eureka

---
spring:
  profiles: eureka2
server:
  port: 8762
eureka:
  instance:
    hostname: eureka2
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka1:8761/eureka,http://eureka3:8763/eureka
      
---
spring:
  profiles: eureka3
server:
  port: 8763
eureka:
  instance:
    hostname: eureka3
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://eureka1:8761/eureka,http://eureka2:8762/eureka
      
#security:
#  basic:
#    enabled: true
#  user:
#    name: admin
#    password: admin