eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8888/eureka/
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html # ${server.port}为该服务的端口号
    
server:
  port: 8080
spring:
  application:
    name: consumer
  devtools:
    restart:
      additional-paths: src/main/java #添加那个目录的文件需要restart
      exclude: static/**,public/**  #排除那个目录的文件不需要restart

feign:
  hystrix:
    enabled: true
