eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8888/eureka/
  instance:
    status-page-url: http://localhost:${server.port}/swagger-ui.html # ${server.port}为该服务的端口号
    
server:
  port: 8080
spring:
  application:
    name: consumer

feign:
  hystrix:
    enabled: true    
    